// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice = VideoSlice;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type CourseDocumentDataSlicesSlice =
  | TrainingCourseSlice
  | SkillSlice
  | StudentSlice
  | TitleMiddleSlice
  | ObjectiveSlice
  | DreamSlice
  | HerosSlice;

/**
 * Content for Course documents
 */
interface CourseDocumentData {
  /**
   * Title field in *Course*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Course*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: course.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CourseDocumentDataSlicesSlice> /**
   * Meta Description field in *Course*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: course.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Course*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: course.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Course*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: course.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Course document from Prismic
 *
 * - **API ID**: `course`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CourseDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<CourseDocumentData>, "course", Lang>;

type InformativeDocumentDataSlicesSlice =
  | QualitySlice
  | MeetSlice
  | StudentSlice
  | ImageRightSlice
  | ImageSlice
  | VideoSlice
  | HerosSlice;

/**
 * Content for Informative documents
 */
interface InformativeDocumentData {
  /**
   * Title field in *Informative*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: informative.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Informative*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: informative.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InformativeDocumentDataSlicesSlice> /**
   * Meta Description field in *Informative*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: informative.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Informative*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: informative.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Informative*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: informative.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Informative document from Prismic
 *
 * - **API ID**: `informative`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InformativeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<InformativeDocumentData>,
    "informative",
    Lang
  >;

type LegalDocumentDataSlicesSlice = HerosSlice | ContentSlice;

/**
 * Content for Legal documents
 */
interface LegalDocumentData {
  /**
   * Title field in *Legal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Legal*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LegalDocumentDataSlicesSlice> /**
   * Meta Description field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legal.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Legal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: legal.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Legal document from Prismic
 *
 * - **API ID**: `legal`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LegalDocumentData>, "legal", Lang>;

type PageDocumentDataSlicesSlice =
  | WorksSlice
  | ImageSlice
  | TitleMiddleSlice
  | ArticleSlice
  | YearSlice
  | TitleSlice
  | CourseSlice
  | VideoSlice
  | HeroSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | ArticleDocument
  | CourseDocument
  | InformativeDocument
  | LegalDocument
  | PageDocument;

/**
 * Primary content in *Article → Primary*
 */
export interface ArticleSliceDefaultPrimary {
  /**
   * Title field in *Article → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Article → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Article → Items*
 */
export interface ArticleSliceDefaultItem {
  /**
   * Image field in *Article → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Place field in *Article → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.items[].place
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  place: prismic.RichTextField;

  /**
   * Title field in *Article → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Date field in *Article → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article.items[].date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Link field in *Article → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: article.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Article Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleSliceDefaultPrimary>,
  Simplify<ArticleSliceDefaultItem>
>;

/**
 * Slice variation for *Article*
 */
type ArticleSliceVariation = ArticleSliceDefault;

/**
 * Article Shared Slice
 *
 * - **API ID**: `article`
 * - **Description**: Article
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleSlice = prismic.SharedSlice<
  "article",
  ArticleSliceVariation
>;

/**
 * Primary content in *Content → Items*
 */
export interface ContentSliceDefaultItem {
  /**
   * Title field in *Content → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Content → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ContentSliceDefaultItem>
>;

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation = ContentSliceDefault;

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSlice = prismic.SharedSlice<
  "content",
  ContentSliceVariation
>;

/**
 * Primary content in *Course → Primary*
 */
export interface CourseSliceDefaultPrimary {
  /**
   * Title field in *Course → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Course → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Course → Items*
 */
export interface CourseSliceDefaultItem {
  /**
   * Title field in *Course → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Tag_1 field in *Course → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course.items[].tag_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tag_1: prismic.RichTextField;

  /**
   * Tag_2 field in *Course → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course.items[].tag_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tag_2: prismic.RichTextField;

  /**
   * Content field in *Course → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Link field in *Course → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: course.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Course Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CourseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CourseSliceDefaultPrimary>,
  Simplify<CourseSliceDefaultItem>
>;

/**
 * Slice variation for *Course*
 */
type CourseSliceVariation = CourseSliceDefault;

/**
 * Course Shared Slice
 *
 * - **API ID**: `course`
 * - **Description**: Course
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CourseSlice = prismic.SharedSlice<"course", CourseSliceVariation>;

/**
 * Primary content in *Dream → Primary*
 */
export interface DreamSliceDefaultPrimary {
  /**
   * Dream field in *Dream → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dream.primary.dream
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  dream: prismic.RichTextField;

  /**
   * Title field in *Dream → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dream.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Dream → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dream.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *Dream → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dream.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Dream Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DreamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DreamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Dream*
 */
type DreamSliceVariation = DreamSliceDefault;

/**
 * Dream Shared Slice
 *
 * - **API ID**: `dream`
 * - **Description**: Dream
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DreamSlice = prismic.SharedSlice<"dream", DreamSliceVariation>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Heros → Primary*
 */
export interface HerosSliceDefaultPrimary {
  /**
   * Title field in *Heros → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heros.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Heros → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heros.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Heros Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HerosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HerosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Heros*
 */
type HerosSliceVariation = HerosSliceDefault;

/**
 * Heros Shared Slice
 *
 * - **API ID**: `heros`
 * - **Description**: Heros
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HerosSlice = prismic.SharedSlice<"heros", HerosSliceVariation>;

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Title field in *Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *ImageRight → Primary*
 */
export interface ImageRightSliceDefaultPrimary {
  /**
   * Title field in *ImageRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *ImageRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *ImageRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageRight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageRightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageRightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageRight*
 */
type ImageRightSliceVariation = ImageRightSliceDefault;

/**
 * ImageRight Shared Slice
 *
 * - **API ID**: `image_right`
 * - **Description**: ImageRight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageRightSlice = prismic.SharedSlice<
  "image_right",
  ImageRightSliceVariation
>;

/**
 * Primary content in *Meet → Primary*
 */
export interface MeetSliceDefaultPrimary {
  /**
   * Title field in *Meet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Meet → Items*
 */
export interface MeetSliceDefaultItem {
  /**
   * Title field in *Meet → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Meet → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *Meet → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: meet.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Meet Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MeetSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MeetSliceDefaultPrimary>,
  Simplify<MeetSliceDefaultItem>
>;

/**
 * Slice variation for *Meet*
 */
type MeetSliceVariation = MeetSliceDefault;

/**
 * Meet Shared Slice
 *
 * - **API ID**: `meet`
 * - **Description**: Meet
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MeetSlice = prismic.SharedSlice<"meet", MeetSliceVariation>;

/**
 * Primary content in *Objective → Primary*
 */
export interface ObjectiveSliceDefaultPrimary {
  /**
   * Title field in *Objective → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: objective.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Objective → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: objective.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Image field in *Objective → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: objective.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Objective Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ObjectiveSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ObjectiveSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Objective*
 */
type ObjectiveSliceVariation = ObjectiveSliceDefault;

/**
 * Objective Shared Slice
 *
 * - **API ID**: `objective`
 * - **Description**: Objective
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ObjectiveSlice = prismic.SharedSlice<
  "objective",
  ObjectiveSliceVariation
>;

/**
 * Primary content in *Quality → Primary*
 */
export interface QualitySliceDefaultPrimary {
  /**
   * Title field in *Quality → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quality.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Quality → Items*
 */
export interface QualitySliceDefaultItem {
  /**
   * Title field in *Quality → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quality.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Quality → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quality.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Quality Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QualitySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QualitySliceDefaultPrimary>,
  Simplify<QualitySliceDefaultItem>
>;

/**
 * Slice variation for *Quality*
 */
type QualitySliceVariation = QualitySliceDefault;

/**
 * Quality Shared Slice
 *
 * - **API ID**: `quality`
 * - **Description**: Quality
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QualitySlice = prismic.SharedSlice<
  "quality",
  QualitySliceVariation
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *Skill → Primary*
 */
export interface SkillSliceDefaultPrimary {
  /**
   * Title field in *Skill → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Skill → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Skill → Items*
 */
export interface SkillSliceDefaultItem {
  /**
   * Title field in *Skill → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Skill → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Skill Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillSliceDefaultPrimary>,
  Simplify<SkillSliceDefaultItem>
>;

/**
 * Slice variation for *Skill*
 */
type SkillSliceVariation = SkillSliceDefault;

/**
 * Skill Shared Slice
 *
 * - **API ID**: `skill`
 * - **Description**: Skill
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillSlice = prismic.SharedSlice<"skill", SkillSliceVariation>;

/**
 * Primary content in *Student → Primary*
 */
export interface StudentSliceDefaultPrimary {
  /**
   * Title field in *Student → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Student → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Student → Items*
 */
export interface StudentSliceDefaultItem {
  /**
   * Image field in *Student → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: student.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Student → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Work field in *Student → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student.items[].work
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  work: prismic.RichTextField;

  /**
   * Companie field in *Student → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student.items[].companie
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  companie: prismic.RichTextField;

  /**
   * LinkedIn field in *Student → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: student.items[].linkedin
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;
}

/**
 * Default variation for Student Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StudentSliceDefaultPrimary>,
  Simplify<StudentSliceDefaultItem>
>;

/**
 * Slice variation for *Student*
 */
type StudentSliceVariation = StudentSliceDefault;

/**
 * Student Shared Slice
 *
 * - **API ID**: `student`
 * - **Description**: Student
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudentSlice = prismic.SharedSlice<
  "student",
  StudentSliceVariation
>;

/**
 * Primary content in *Title → Primary*
 */
export interface TitleSliceDefaultPrimary {
  /**
   * title field in *Title → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Title → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Title Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Title*
 */
type TitleSliceVariation = TitleSliceDefault;

/**
 * Title Shared Slice
 *
 * - **API ID**: `title`
 * - **Description**: Title
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSlice = prismic.SharedSlice<"title", TitleSliceVariation>;

/**
 * Primary content in *TitleMiddle → Primary*
 */
export interface TitleMiddleSliceDefaultPrimary {
  /**
   * Title field in *TitleMiddle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_middle.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *TitleMiddle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_middle.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TitleMiddle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleMiddleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleMiddleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleMiddle*
 */
type TitleMiddleSliceVariation = TitleMiddleSliceDefault;

/**
 * TitleMiddle Shared Slice
 *
 * - **API ID**: `title_middle`
 * - **Description**: TitleMiddle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleMiddleSlice = prismic.SharedSlice<
  "title_middle",
  TitleMiddleSliceVariation
>;

/**
 * Primary content in *TrainingCourse → Primary*
 */
export interface TrainingCourseSliceDefaultPrimary {
  /**
   * Title field in *TrainingCourse → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_course.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *TrainingCourse → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: training_course.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *TrainingCourse → Items*
 */
export interface TrainingCourseSliceDefaultItem {
  /**
   * Title field in *TrainingCourse → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_course.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *TrainingCourse → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_course.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Link field in *TrainingCourse → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: training_course.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for TrainingCourse Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrainingCourseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TrainingCourseSliceDefaultPrimary>,
  Simplify<TrainingCourseSliceDefaultItem>
>;

/**
 * Slice variation for *TrainingCourse*
 */
type TrainingCourseSliceVariation = TrainingCourseSliceDefault;

/**
 * TrainingCourse Shared Slice
 *
 * - **API ID**: `training_course`
 * - **Description**: TrainingCourse
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrainingCourseSlice = prismic.SharedSlice<
  "training_course",
  TrainingCourseSliceVariation
>;

/**
 * Primary content in *Video → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * Title field in *Video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Video field in *Video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video.primary.video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

/**
 * Primary content in *Works → Primary*
 */
export interface WorksSliceDefaultPrimary {
  /**
   * Title field in *Works → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Works → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Works → Items*
 */
export interface WorksSliceDefaultItem {
  /**
   * Image field in *Works → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Works → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Works → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Link field in *Works → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: works.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Works Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorksSliceDefaultPrimary>,
  Simplify<WorksSliceDefaultItem>
>;

/**
 * Slice variation for *Works*
 */
type WorksSliceVariation = WorksSliceDefault;

/**
 * Works Shared Slice
 *
 * - **API ID**: `works`
 * - **Description**: Works
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksSlice = prismic.SharedSlice<"works", WorksSliceVariation>;

/**
 * Primary content in *Year → Primary*
 */
export interface YearSliceDefaultPrimary {
  /**
   * Title field in *Year → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: year.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Year → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: year.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Year → Items*
 */
export interface YearSliceDefaultItem {
  /**
   * Year field in *Year → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: year.items[].year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year: prismic.RichTextField;

  /**
   * Title field in *Year → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: year.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Year → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: year.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Year Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YearSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<YearSliceDefaultPrimary>,
  Simplify<YearSliceDefaultItem>
>;

/**
 * Slice variation for *Year*
 */
type YearSliceVariation = YearSliceDefault;

/**
 * Year Shared Slice
 *
 * - **API ID**: `year`
 * - **Description**: Year
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YearSlice = prismic.SharedSlice<"year", YearSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      CourseDocument,
      CourseDocumentData,
      CourseDocumentDataSlicesSlice,
      InformativeDocument,
      InformativeDocumentData,
      InformativeDocumentDataSlicesSlice,
      LegalDocument,
      LegalDocumentData,
      LegalDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ArticleSlice,
      ArticleSliceDefaultPrimary,
      ArticleSliceDefaultItem,
      ArticleSliceVariation,
      ArticleSliceDefault,
      ContentSlice,
      ContentSliceDefaultItem,
      ContentSliceVariation,
      ContentSliceDefault,
      CourseSlice,
      CourseSliceDefaultPrimary,
      CourseSliceDefaultItem,
      CourseSliceVariation,
      CourseSliceDefault,
      DreamSlice,
      DreamSliceDefaultPrimary,
      DreamSliceVariation,
      DreamSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HerosSlice,
      HerosSliceDefaultPrimary,
      HerosSliceVariation,
      HerosSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageRightSlice,
      ImageRightSliceDefaultPrimary,
      ImageRightSliceVariation,
      ImageRightSliceDefault,
      MeetSlice,
      MeetSliceDefaultPrimary,
      MeetSliceDefaultItem,
      MeetSliceVariation,
      MeetSliceDefault,
      ObjectiveSlice,
      ObjectiveSliceDefaultPrimary,
      ObjectiveSliceVariation,
      ObjectiveSliceDefault,
      QualitySlice,
      QualitySliceDefaultPrimary,
      QualitySliceDefaultItem,
      QualitySliceVariation,
      QualitySliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SkillSlice,
      SkillSliceDefaultPrimary,
      SkillSliceDefaultItem,
      SkillSliceVariation,
      SkillSliceDefault,
      StudentSlice,
      StudentSliceDefaultPrimary,
      StudentSliceDefaultItem,
      StudentSliceVariation,
      StudentSliceDefault,
      TitleSlice,
      TitleSliceDefaultPrimary,
      TitleSliceVariation,
      TitleSliceDefault,
      TitleMiddleSlice,
      TitleMiddleSliceDefaultPrimary,
      TitleMiddleSliceVariation,
      TitleMiddleSliceDefault,
      TrainingCourseSlice,
      TrainingCourseSliceDefaultPrimary,
      TrainingCourseSliceDefaultItem,
      TrainingCourseSliceVariation,
      TrainingCourseSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
      WorksSlice,
      WorksSliceDefaultPrimary,
      WorksSliceDefaultItem,
      WorksSliceVariation,
      WorksSliceDefault,
      YearSlice,
      YearSliceDefaultPrimary,
      YearSliceDefaultItem,
      YearSliceVariation,
      YearSliceDefault,
    };
  }
}
