// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  article: defineAsyncComponent(() => import("./Article/index.vue")),
  course: defineAsyncComponent(() => import("./Course/index.vue")),
  dream: defineAsyncComponent(() => import("./Dream/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  heros: defineAsyncComponent(() => import("./Heros/index.vue")),
  image: defineAsyncComponent(() => import("./Image/index.vue")),
  image_right: defineAsyncComponent(() => import("./ImageRight/index.vue")),
  meet: defineAsyncComponent(() => import("./Meet/index.vue")),
  objective: defineAsyncComponent(() => import("./Objective/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  skill: defineAsyncComponent(() => import("./Skill/index.vue")),
  student: defineAsyncComponent(() => import("./Student/index.vue")),
  title: defineAsyncComponent(() => import("./Title/index.vue")),
  title_middle: defineAsyncComponent(() => import("./TitleMiddle/index.vue")),
  training_course: defineAsyncComponent(
    () => import("./TrainingCourse/index.vue"),
  ),
  video: defineAsyncComponent(() => import("./Video/index.vue")),
  works: defineAsyncComponent(() => import("./Works/index.vue")),
  year: defineAsyncComponent(() => import("./Year/index.vue")),
});
