// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  article: defineAsyncComponent(() => import("./Article/index.vue")),
  course: defineAsyncComponent(() => import("./Course/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  title: defineAsyncComponent(() => import("./Title/index.vue")),
  video: defineAsyncComponent(() => import("./Video/index.vue")),
  year: defineAsyncComponent(() => import("./Year/index.vue")),
});
